"""
Shared data models for the SkillForge multi-agent system.

Data Flow in the Multi-Agent System:
------------------------------------
The `SkillBlueprint` acts as the central contract flowing through the system:

1. RootAgent -> PlannerAgent: 
   The user request is parsed, and the PlannerAgent creates a populated `SkillBlueprint`.
   
2. PlannerAgent -> GeneratorAgent: 
   The generated `SkillBlueprint` is passed to the GeneratorAgent. The GeneratorAgent 
   reads these structured requirements (purpose, workflow, tools, etc.) to construct 
   the first draft of a SKILL.md file.

3. GeneratorAgent -> ReviewerAgent:
   The ReviewerAgent receives both the generated SKILL.md draft and the original 
   `SkillBlueprint`. It evaluates the draft against the blueprint's `success_criteria`, 
   `constraints`, and `workflow_steps` to ensure high quality before final output.
"""

from typing import List, Dict, Any
from pydantic import BaseModel, Field

class SkillBlueprint(BaseModel):
    """
    SkillBlueprint represents the structured requirements and design for an AI Agent Skill.
    """
    title: str = Field(..., description="The name of the skill")
    description: str = Field(..., description="A brief description of what the skill does")
    purpose: str = Field(..., description="The primary goal or problem this skill solves")
    target_users: List[str] = Field(default_factory=list, description="Who is expected to use this skill")
    
    inputs: List[str] = Field(default_factory=list, description="Expected inputs provided to the skill")
    outputs: List[str] = Field(default_factory=list, description="Expected outputs generated by the skill")
    required_tools: List[str] = Field(default_factory=list, description="Tools the agent needs access to to execute this skill")
    
    workflow_steps: List[str] = Field(default_factory=list, description="Step-by-step logic the skill should follow")
    constraints: List[str] = Field(default_factory=list, description="Limitations, rules, or boundaries the skill must respect")
    failure_cases: List[str] = Field(default_factory=list, description="Known edge cases or situations where the skill might fail")
    success_criteria: List[str] = Field(default_factory=list, description="Metrics or conditions to determine if the skill succeeded")
    
    example_prompt: str = Field(..., description="An example user prompt triggering this skill")
    expected_response: str = Field(..., description="The expected response or output for the example prompt")
    
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context, configuration, or arbitrary key-value pairs")

class ParsedRequest(BaseModel):
    """
    ParsedRequest represents the normalized intent extracted from a user's natural-language request.
    This structured data is generated by the Request Parser tool before any planning begins.
    """
    goal: str = Field(..., description="The primary objective the user wants the skill to achieve")
    domain: str = Field(..., description="The subject area or domain of the requested skill (e.g., coding, creative writing)")
    skill_type: str = Field(..., description="The category or type of the skill (e.g., 'research', 'code generation', 'analysis')")
    target_users: List[str] = Field(default_factory=list, description="Who the skill is intended for")
    expected_outputs: List[str] = Field(default_factory=list, description="What the user expects the skill to produce")
    constraints: List[str] = Field(default_factory=list, description="Rules, boundaries, or limitations specified by the user")
    required_tools: List[str] = Field(default_factory=list, description="Any specific tools the user mentioned the skill should use")
    quality_requirements: List[str] = Field(default_factory=list, description="Specific quality benchmarks or standards the skill must meet")
    missing_information: List[str] = Field(default_factory=list, description="Ambiguities or missing details that need clarification")

class ReviewResult(BaseModel):
    """
    ReviewResult encapsulates the structured feedback and evaluation of a generated Skill Package.
    It is produced by the ReviewerAgent to determine if the skill meets the required quality.
    """
    sqi_score: float = Field(..., description="The calculated Skill Quality Index (SQI) score")
    passed: bool = Field(..., description="Whether the skill package met the minimum quality threshold")
    revision_required: bool = Field(..., description="Whether the generator needs to revise the skill package")
    strengths: List[str] = Field(default_factory=list, description="Positive aspects identified in the skill package")
    weaknesses: List[str] = Field(default_factory=list, description="Areas where the skill package falls short")
    feedback: str = Field(..., description="Detailed feedback summarizing the review")
    suggested_improvements: List[str] = Field(default_factory=list, description="Specific, actionable steps to improve the skill package")
